# Generated by Django 5.2.1 on 2025-07-25 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Серийный номер')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик')),
                ('decommissioned_equipment', models.BooleanField(default=False, verbose_name='Списана ли техника')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/images/%Y/%m/%d', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('inverter_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Инвентарный  номер')),
                ('invoice_info', models.CharField(blank=True, help_text='Реквизиты счета или договора поставки', max_length=255, null=True, verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Уникальное название объекта', max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Типы техники',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Уникальное название объекта', max_length=100, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(help_text='Аббревиатура или короткое название (например: "СЗ НЛ")', max_length=50, verbose_name='Короткое название')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридическое лица',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Уникальное название объекта', max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
