# Generated by Django 5.2.1 on 2025-07-25 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия или отказа от техники')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'История передачи оборудования',
                'verbose_name_plural': 'История передачи оборудования',
                'ordering': ['-requested_at'],
            },
        ),
    ]
