# Generated by Django 5.2.1 on 2025-08-04 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_position_alter_customuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(help_text='Уникальное название объекта', max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
