# Generated by Django 5.2.1 on 2025-08-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_position_public_id_alter_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание должности'),
        ),
    ]
